import * as bodyParser from 'body-parser';
import * as cors from 'cors';
import * as express from 'express';
import * as helmet from 'helmet';
import * as morgan from 'morgan';
import 'reflect-metadata';
import * as swaggerJSDoc from 'swagger-jsdoc';
import * as swaggerStats from 'swagger-stats';
import * as swaggerUi from 'swagger-ui-express';
import { AppDataSource } from './config/datasource';
import routes from './routes';

const options = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
    },
  },
  // List of files to be processes. You can also set globs './routes/*.js'
  apis: ['**/routes/auth.ts', '**/controller/Admin/*.ts'],
};

const specs = swaggerJSDoc(options);

// Connects to the Database -> then starts the express
AppDataSource.initialize()
  .then(() => {
    console.log('Data Source has been initialized!');
    
    // Create a new express application instance
    const app = express();
    
    // Call middlewares
    app.use(cors());
    app.use(swaggerStats.getMiddleware({}));
    app.use(helmet());
    app.use(bodyParser.json());
    
    // Morgan logging setup
    morgan.token('header-auth', (req, res) => req.headers.auth as string);
    morgan.token('body', (req, res) => JSON.stringify(req.body));
    app.use(morgan('[:date[web]] Started :method :url for :remote-addr'));
    app.use(morgan('[:date[web]] Started with token :header-auth'));
    app.use(morgan('[:date[web]] Started with body :body'));
    app.use(
      morgan(
        '[:date[iso]] Completed :status :res[content-length] in :response-time ms',
      ),
    );
    
    // Set all routes from routes folder
    app.use('/', routes);
    app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));
    
    // Health check endpoint
    app.get('/health', (req, res) => {
      res.status(200).json({ status: 'OK', timestamp: new Date().toISOString() });
    });
    
    app.listen(3000, () => {
      console.log('Server started on port 3000!');
    });
  })
  .catch((error) => console.log('Error during Data Source initialization:', error));
