version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: cia_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cia_network

  api:
    image: node:16
    container_name: cia_api
    build:
      context: ./back_student
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: dev_db
    depends_on:
      - db
    volumes:
      - ./back_student:/usr/src/app
    networks:
      - cia_network

volumes:
  mysql_data:

networks:
  cia_network:
    driver: bridge
