services:
  - type: web
    name: cia-backend-api
    runtime: node
    repo: https://gitlab.com/cello-miao-group/CIA-Project.git
    branch: xinxin
    rootDir: back_student
    buildCommand: npm ci && npm run build
    startCommand: node build/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://cia-frontend-web.onrender.com
      - key: DEFAULT_ADMIN_USERNAME
        value: admin
      - key: DEFAULT_ADMIN_PASSWORD
        value: Kh3$bF6&nT1*pY9vXc2@Dm5
      - key: DATABASE_URL
        fromDatabase:
          name: cia-mysql-db
          property: connectionString

  - type: web
    name: cia-frontend-web
    runtime: static
    repo: https://gitlab.com/cello-miao-group/CIA-Project.git
    branch: xinxin
    rootDir: front_student
    buildCommand: npm ci --ignore-scripts && echo "REACT_APP_API_URL=https://cia-backend-api-kth2.onrender.com" > .env && NODE_OPTIONS=--openssl-legacy-provider npm run build && cp public/_redirects build/
    staticPublishPath: ./build
    errorPage: index.html

databases:
  - name: cia-mysql-db
    databaseName: cia_db
    user: cia_user
    plan: free
