name: CIA Project Basic Integration Suite

on:
  push:
    branches: [ahmad, master]
  pull_request:
    branches: [ahmad, master]
  workflow_dispatch: {}

jobs:
  basic-integration-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Test Backend Compilations
        run: |
          cd back_student
          yarn install --frozen-lockfile
          yarn build

      - name: Test Frontend Compilations
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          cd front_student
          npm ci --ignore-scripts
          npm run build

      - name: Populate Local Runner Configuration
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          DEFAULT_ADMIN_PASSWORD: ${{ secrets.DEFAULT_ADMIN_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          echo "::add-mask::${MYSQL_ROOT_PASSWORD}"
          echo "::add-mask::${DEFAULT_ADMIN_PASSWORD}"
          echo "::add-mask::${JWT_SECRET}"
          echo "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" >> .env
          echo "MYSQL_DATABASE=cia_db" >> .env
          echo "API_INTERNAL_PORT=3001" >> .env
          echo "DEFAULT_ADMIN_USERNAME=admin" >> .env
          echo "DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}" >> .env
          echo "JWT_SECRET=${JWT_SECRET}" >> .env
